
$accent = rgb(a277ff)
$accentAlpha = a277ff
$base = 29263c
$font = IosevkaNerdFontMono
$surface = 3d375e7f
$text = edecee
$yellow = rgb(ffca85)
$red = rgb(ff6767)

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = ~/wallpapers/wallpaper-abstract.jpg
    blur_passes = 2
    color = $base
}

# TIME
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = $text
    font_size = 90
    font_family = $font
    position = -30, 0
    halign = right
    valign = top
}

# DATE 
label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $text
    font_size = 25
    font_family = $font
    position = -30, -150
    halign = right
    valign = top
}


# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = rgba(41,38,60,1.0)
    font_color = rgba(237,236,238, 1.0)
    fade_on_empty = false
    placeholder_text = <span foreground="##$text"><i>Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
    hide_input = false
    check_color = $yellow
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 0, 0
    halign = center
    valign = center
}
